# Generated by Django 5.1.1 on 2024-10-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_subscription_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='renewal',
            field=models.BooleanField(default=False),
        ),
    ]
