# Generated by Django 5.1.1 on 2024-10-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='time',
            field=models.IntegerField(default=30),
        ),
    ]
